--创建部门表
CREATE TABLE TS_DEPT(
       DPID NUMBER PRIMARY KEY,
       UPDPID NUMBER NOT NULL,
       DPNAME VARCHAR2(50) NOT NULL,
       DPSTATE NUMBER DEFAULT 1,
       DPLEVEL NUMBER NOT NULL,
       DPDESC VARCHAR2(200)
)

INSERT INTO TS_DEPT(DPID,UPDPID,DPNAME,DPSTATE,DPLEVEL,DPDESC)VALUES(SEQ_TS_DEPT.NEXTVAL,0,'国务院',1,1,'最高级别部门')

--部门表SEQ
CREATE SEQUENCE SEQ_TS_DEPT ;
--创建用户表
CREATE TABLE TS_USER(
       USID NUMBER PRIMARY KEY,
       USACCT VARCHAR2(20) NOT NULL UNIQUE,
       USNAME VARCHAR2(20) NOT NULL,
       USREALNAME VARCHAR2(20),
       USPASS VARCHAR2(20)  DEFAULT '123456',
       DPID NUMBER NOT NULL REFERENCES TS_DEPT(DPID),
       USPHONE VARCHAR2(20),
       USEMAIL VARCHAR2(30),
       USTATE NUMBER DEFAULT 1,
       USCARDNO VARCHAR2(32),
       CREATEDATE DATE  DEFAULT SYSDATE,
       LOGINAGAIN NUMBER DEFAULT -1
)
--用户表SEQ
CREATE SEQUENCE SEQ_TS_USER;
SELECT U.*,ROWID FROM TS_USER U;
INSERT INTO TS_USER(USID,USACCT,USNAME,USREALNAME,USPASS,DPID,USPHONE)VALUES(SEQ_TS_USER.NEXTVAL,'admin','系统管理员','系统管理员','123456',1,'18956032431')
--创建角色表
CREATE TABLE TS_ROLE(
       ROID NUMBER PRIMARY KEY,
       RONAME VARCHAR2(30) NOT NULL,
       ROTYPE NUMBER DEFAULT 1,
       ROSTATE NUMBER DEFAULT 1,
       RODESC VARCHAR2(200)
)
--角色表SEQ
CREATE SEQUENCE SEQ_TS_ROLE;

--用户角色映射表
CREATE TABLE TS_USER_ROLE(
       USID NUMBER NOT NULL REFERENCES TS_USER(USID),
       ROID NUMBER NOT NULL REFERENCES TS_ROLE(ROID),
       CONSTRAINTS TS_USER_ROLE_PK PRIMARY KEY(USID,ROID)
)
--创建菜单表
CREATE TABLE TS_MENU(
       MUID NUMBER PRIMARY KEY,
       MUNAME VARCHAR2(20) NOT NULL,
       UPMUID NUMBER NOT NULL,
       MUICON VARCHAR2(20) DEFAULT 'icon-question-sign',
       MULINK VARCHAR2(300),
       MULEVEL NUMBER NOT NULL,
       MUTITLE VARCHAR2(100),
       MUSTATE NUMBER DEFAULT 1,
       MUORDER NUMBER DEFAULT 1,
       MUTYPE VARCHAR2(20) NOT NULL      
)
--菜单表SEQ
CREATE SEQUENCE SEQ_TS_MENU;

select m.*,rowid from TS_MENU m;

insert into ts_menu(muid,muname,upmuid,muicon,mulink,mulevel,mutitle,mustate,muorder,mutype)values(SEQ_TS_MENU.Nextval,'系统管理模块','0','icon-dashboard','<%=path%>/sys/index',
1,'',1,1,'Application')


--功能权限表
CREATE TABLE TS_PRIVILEGE(
       PVID NUMBER PRIMARY KEY,
       PVMASTER VARCHAR2(20) NOT NULL,
       PVMASTERVALUE VARCHAR2(30) NOT NULL,
       PVACCESS VARCHAR2(20) NOT NULL,
       PVACCESSVALUE VARCHAR2(30) NOT NULL,
       PVOPERATION VARCHAR2(50) NOT NULL
)
--功能权限表SEQ
CREATE SEQUENCE SEQ_TS_PRIVILEGE;
SELECT v.*,rowid FROM TS_PRIVILEGE v;
INSERT INTO TS_PRIVILEGE(PVID,PVMASTER,PVMASTERVALUE,PVACCESS,PVACCESSVALUE,PVOPERATION)VALUES(SEQ_TS_PRIVILEGE.Nextval,'User','1','Menu','3','Available')


--数据权限类型表(TS_DATACSTYPE)
CREATE TABLE TS_DATACSTYPE(
       DTCSTYPE NUMBER PRIMARY KEY,
       DTCSTYPENAME VARCHAR2(20) NOT NULL
)
--数据权限类型表SEQ
CREATE SEQUENCE SEQ_TS_DATACSTYPEE;

--数据权限表(TS_DATACS)
CREATE TABLE TS_DATACS(
       DTCSID NUMBER PRIMARY KEY,
       DTCSVALUE VARCHAR2(20),
       DTCSUPID NUMBER NOT NULL,
       DTCSTYPE NUMBER REFERENCES TS_DATACSTYPE(DTCSTYPE),
       DTCSMEMO VARCHAR2(100)
)
--数据权限表SEQ
CREATE SEQUENCE SEQ_TS_DATACS;

--用户数据权限映射表(TS_USER_DATACS)
CREATE TABLE TS_USER_DATACS(
       USID NUMBER NOT NULL REFERENCES TS_USER(USID),
       DTCSID NUMBER NOT NULL REFERENCES TS_DATACS(DTCSID),
       CONSTRAINTS TS_USER_DATACS_PK PRIMARY KEY(USID,DTCSID)
)

--字典表
CREATE TABLE TS_DICTABLE(
       DID NUMBER PRIMARY KEY,
       DNAME VARCHAR2(20) NOT NULL,
       DTYPE VARCHAR2(20) NOT NULL,
       DVAL VARCHAR2(20) NOT NULL,
       DSTATE NUMBER DEFAULT 1,
       DDESC VARCHAR2(50)
)
--字典表SEQ
CREATE SEQUENCE SEQ_TS_DICTABLE;

--操作日志表TL_OPERATE_LOG
CREATE TABLE TL_OPERATE_LOG(
       LOGID NUMBER PRIMARY KEY,
       USID NUMBER NOT NULL,
       MODULAR varchar(30) NOT NULL,
       OPERTYPE VARCHAR2(20) NOT NULL,
       OPERCONTEXT VARCHAR2(300),
       OPERDATE DATE DEFAULT SYSDATE,
       LOGLEVEL VARCHAR2(10) NOT NULL,
       IPADDRESS VARCHAR2(50)
)
--字典表SEQ
CREATE SEQUENCE SEQ_TL_OPERATE_LOG;

--区域表(TD_AREA)
CREATE TABLE TD_AREA(
       AREAID NUMBER PRIMARY KEY,
       AREANAME VARCHAR2(20),
       UPAREAID NUMBER NOT NULL,
       AREALEVEL NUMBER NOT NULL,
       AREACODE VARCHAR2(20),
       AREASTATE NUMBER DEFAULT 1,
       AREAORDER NUMBER 
)